name: Feature request
description: Suggest an improvement.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What would you like to do that you cannot do now?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: How could it work?
