// Writes THIRD_PARTY_NOTICES.md from the installed production packages.
//
// The file lists packages and licenses, not versions. It changes only when a
// package is added or removed or a license changes, which is when a person
// should look at it; a version bump leaves it as it is, so CI can check that
// it is up to date without failing every dependency update.
//
// Lists the libraries embedded into generated units (assets/vendor.json),
// the packages they bundle (their own runtime dependencies, recursively),
// and the build-time tools. Run after `npm ci` and whenever package-lock.json
// changes:   node scripts/third_party_notices.mjs
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const pkg = name => JSON.parse(readFileSync(`node_modules/${name}/package.json`, "utf-8"));
// Packages without a license field: read the first line of their license file.
function fromFile(name) {
  for (const f of ["LICENSE", "LICENSE.md", "license", "license.md", "LICENSE.txt"]) {
    const path = `node_modules/${name}/${f}`;
    if (existsSync(path)) {
      const first = readFileSync(path, "utf-8").split("\n").find(l => l.trim()) || "";
      if (/MIT/.test(first)) return "MIT";
      if (/ISC/.test(first)) return "ISC";
      return first.trim().slice(0, 40);
    }
  }
  return "see package";
}
const license = p => typeof p.license === "string" ? p.license
  : (p.license && p.license.type) || (p.licenses || []).map(l => l.type || l).join(" OR ")
    || fromFile(p.name);

function closure(root) {
  const seen = new Map(), stack = [root];
  while (stack.length) {
    const name = stack.pop();
    if (seen.has(name) || !existsSync(`node_modules/${name}/package.json`)) continue;
    const p = pkg(name); seen.set(name, p);
    for (const dep of Object.keys(p.dependencies || {})) stack.push(dep);
  }
  seen.delete(root);
  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
}

const manifest = JSON.parse(readFileSync("assets/vendor.json", "utf-8"));
const embedded = [...new Set(Object.entries(manifest).filter(([k]) => !k.startsWith("_"))
  .flatMap(([, v]) => v).map(e => e.package))];
const buildOnly = ["katex", "jsdom", "dompurify"];

const rows = [];
rows.push("# Third-party notices", "",
  "Generated by `scripts/third_party_notices.mjs` from the installed packages.", "",
  "## Embedded into generated units", "",
  "A generated unit contains only the libraries it uses. Each file keeps the",
  "license notice its project ships with it. \"Bundles\" lists the library's",
  "runtime dependencies, recursively. That is an upper bound: some of them",
  "are used only by the library's command-line tools and are not part of the",
  "browser bundle.", "",
  "| Library | License | Bundles |", "|---|---|---|");
for (const name of embedded) {
  const p = pkg(name);
  const bundled = closure(name).map(d => `${d.name} (${license(d)})`).join(", ") || "—";
  rows.push(`| ${name} | ${license(p)} | ${bundled} |`);
}
rows.push("", "## Used at build time only", "",
  "Run by the Node probes while a unit is generated; nothing of them is in a unit.", "",
  "| Package | License |", "|---|---|");
for (const name of buildOnly) { const p = pkg(name); rows.push(`| ${name} | ${license(p)} |`); }
rows.push("", "## Python packages", "",
  "Installed from `requirements.txt`; licenses as published on PyPI:", "",
  "| Package | License |", "|---|---|",
  "| gradio | Apache-2.0 |", "| openai | Apache-2.0 |", "| python-docx | MIT |",
  "| python-pptx | MIT |", "| pdfminer.six | MIT |", "| python-dotenv | BSD-3-Clause |",
  "| httpx | BSD-3-Clause |", "");
writeFileSync("THIRD_PARTY_NOTICES.md", rows.join("\n"));
console.log(`THIRD_PARTY_NOTICES.md: ${embedded.length} embedded libraries`);
